[workspace]

members = [
    'abc049_c',
    'abc081_a',
    'abc081_b',
    'abc083_b',
    'abc085_b',
    'abc085_c',
    'abc086_a',
    'abc086_c',
    'abc087_b',
    'abc088_b',
    'practice_a',
]
